import machine
import utime
led_external0 = machine.Pin(0, machine.Pin.OUT)
led_external1 = machine.Pin(1, machine.Pin.OUT)
led_external3 = machine.Pin(3, machine.Pin.OUT)
led_external4 = machine.Pin(4, machine.Pin.OUT)
led_external5 = machine.Pin(5, machine.Pin.OUT)
led_external6 = machine.Pin(6, machine.Pin.OUT)
led_external7= machine.Pin(7, machine.Pin.OUT)
led_external8 = machine.Pin(8, machine.Pin.OUT)
led_external9= machine.Pin(9, machine.Pin.OUT)
led_external10= machine.Pin(10, machine.Pin.OUT)
led_external11= machine.Pin(11, machine.Pin.OUT)
led_external12= machine.Pin(12, machine.Pin.OUT)
led_external13= machine.Pin(13, machine.Pin.OUT)

while True:
 led_external0.value(1)
 utime.sleep(0.06)
 led_external1.value(1)
 utime.sleep(0.06)
 led_external3.value(1)
 utime.sleep(0.06)
 led_external4.value(1)
 utime.sleep(0.06)
 led_external5.value(1)
 utime.sleep(0.06)
 led_external6.value(1)
 utime.sleep(0.06)
 led_external7.value(1)
 utime.sleep(0.06)
 led_external8.value(1)
 utime.sleep(0.06)
 led_external9.value(1)
 utime.sleep(0.06)
 led_external10.value(1)
 utime.sleep(0.06)
 led_external11.value(1)
 utime.sleep(0.06)
 led_external12.value(1)
 utime.sleep(0.06)
 led_external13.value(1)
 utime.sleep(0.06)
 led_external0.value(0)
 utime.sleep(0.05)
 led_external1.value(0)
 utime.sleep(0.05)
 led_external3.value(0)
 utime.sleep(0.05)
 led_external4.value(0)
 utime.sleep(0.05)
 led_external5.value(0)
 utime.sleep(0.05)
 led_external6.value(0)
 utime.sleep(0.05)
 led_external7.value(0)
 utime.sleep(0.05)
 led_external8.value(0)
 utime.sleep(0.05)
 led_external9.value(0)
 utime.sleep(0.05)
 led_external10.value(0)
 utime.sleep(0.05)
 led_external11.value(0)
 utime.sleep(0.05)
 led_external12.value(0)
 utime.sleep(0.05)
 led_external13.value(0)
 utime.sleep(0.05)
 